const { Message, message, MessageEmbed, MessageFlags } = require('discord.js')

exports.exec = async function CMDs(client, message, args, cmd) {
    let prefix = require('../../config.json');
    let cmdEmbed = new MessageEmbed()   
    .setColor('PURPLE')
    //.setThumbnail(`${client.user.displayAvatarURL}`)
    .setAuthor(`${message.author.tag}`)
    /* .addFields(
        { name: 'Command List: ', value: 'List of all commands for the bot.' },
        { name: `-----------------------\n😃 Fun commands:`, value: `**${prefix.prefix}bam** - Tap someone on the cranium!\n**${prefix.prefix}bonk** - Bonk someone should they step out of line!\n**${prefix.prefix}pfp** - If you want to be "that guy" and steal someones profile picture... :)\n**${prefix.prefix}kill** - Give the stabby stab to someone who dare stand in your way. >:)\n**${prefix.prefix}cookie** - Give a member a delicious cookie baked fresh!\n**${prefix.prefix}listgames** - Gives a list of different games you can play with the bot.\n**${prefix.prefix}dailynumber** - Lists numbers that may bring you luck. (I hope!)\n**${prefix.prefix}gayrate** - Tells you what percentage of gay you are.\n**${prefix.prefix}simprate** - Tells you what percentage of simp you are.\n**${prefix.prefix}karenrate** - Tells you what percent you are of a raging karen.\n**${prefix.prefix}pp** - Tells you how big your ding dong is. 0_0\n-----------------------`},
        { name: '🎰 Gambling:', value: `**${prefix.prefix}slots** - A generic slot machine to fufill your needs.\n**${prefix.prefix}fish** - Fishing simulator 2021. (100% accurate)\n-----------------------` },
        { name: `⛏ Hypixel/Minecraft:`, value: `**${prefix.prefix}sm - Currently only a test command.\n-----------------------` },
        { name: `⚙️ Utility commands: `, value: `**${prefix.prefix}ping** - Check this bots ping.\n**${prefix.prefix}stats** - Check the bots server statistics.\n**${prefix.prefix}help** - Shows an interactive help menu!\n**${prefix.prefix}info** - Displays any relevant info about the bot.\n**${prefix.prefix}userinfo** - Display info about another users account.\n**${prefix.prefix}cmds** - Displays this menu! (duh.)\n**${prefix.prefix}time** - WIP until bot has funding. \¯\\\_\(\ツ\)\_\/\¯\n**${prefix.prefix}ticket** - WIP ticket system.\n**${prefix.prefix}BIOS** - displays info about the host systems BIOS.\n**${prefix.prefix}CheckGPU** - Currently have no plans for this.\n**${prefix.prefix}CPU** - Displays useful info about the host CPU.\n**${prefix.prefix}CPUSpeed** - Displays useful info about CPU speeds.\n**${prefix.prefix}Disk** - Displays relevant info about host Storage sytem.\n**${prefix.prefix}GPU** - Displays all info about the host GPU.\n**${prefix.prefix}Memory** - Shows all relevant info about the memory allocation.\n**${prefix.prefix}Memlayout** - Displays type of memory used by the host.\n**${prefix.prefix}Motherboard** - Displays host motherboard info.\n**${prefix.prefix}OSInfo** - Shows any info about the host OS.\n**${prefix.prefix}Reload** - Reloads the bot and restarts it.\n**${prefix.prefix}sysinfo** - Displays all info about the bots host system.\n**${prefix.prefix}network** - Displays info about the host's network interface info.\n**${prefix.prefix}wifi** - Displays all info related to the hosts connection.\n-----------------------` },
        { name: `⚒️ Admin commands: `, value: `**${prefix.prefix}kick** - Kick any rule breakers!\n**${prefix.prefix}ban** - Show who's boss by removing a user indefinitely.\n**${prefix.prefix}purge** - Gets rid of the horrible spam messages for you.\n**${prefix.prefix}mute** - Silence anyone who is against you!\n**${prefix.prefix}warn** - Warn someone should they break a minor rule.\n**${prefix.prefix}logs** - Creates a new channel specifically to admins for logging.\n**${prefix.prefix}unban** - This feature is currently a work in progress, stay tuned.\n**${prefix.prefix}unmute** - Unmute a user manually, rather than auto-unmute.\n**${prefix.prefix}Hoist** - Allows for users to give themselves higher roles.\n**${prefix.prefix}delrole** - Deletes a selected role in your guild.\n-----------------------` }
    ) */
    .addFields(
        { name: 'Command List: ', value: 'List of all commands currently.\n-----------------------' },
        /* { name: '😃 Fun Commands:', value: `**${prefix.prefix}bam** - Tap someone on the cranium!\n**${prefix.prefix}bonk** - Bonk someone should they step out of line!\n**${prefix.prefix}kill** - Give the stabby stab to someone who dare stand in your way. >:)\n**${prefix.prefix}cookie** - Give a member a delicious cookie baked fresh!\n**${prefix.prefix}listgames** - Gives a list of different games you can play with the bot.\n**${prefix.prefix}dailynumber** - Lists numbers that may bring you luck. (I hope!)\n**${prefix.prefix}gayrate** - Tells you what percentage of gay you are.\n**${prefix.prefix}simprate** - Tells you what percentage of simp you are.\n**${prefix.prefix}karenrate** - Tells you what percent you are of a raging karen.\n**${prefix.prefix}pp** - Tells you how big your ding dong is. 0_0\n-----------------------`},
        { name: '🎰 Gambling Commands:', value: `**${prefix.prefix}slots** - A generic slot machine to fufill your needs.\n**${prefix.prefix}fish** - Fishing simulator 2021. (100% accurate)\n-----------------------`},
        { name: '⛏ Hypixel/Minecraft:', value: `**${prefix.prefix}sm** - Currently only a test command.\n-----------------------`},
        { name: '📶 Network Commands:', value: `**${prefix.prefix}network** - Displays info about the host's network interface info.\n**${prefix.prefix}wifi** - Displays all info related to the hosts connection.\n-----------------------`},
        { name: '💻 Host System Info:', value: `**${prefix.prefix}BIOS** - displays info about the host systems BIOS.\n**${prefix.prefix}CheckGPU** - Currently have no plans for this.\n**${prefix.prefix}CPU** - Displays useful info about the host CPU.\n**${prefix.prefix}CPUSpeed** - Displays useful info about CPU speeds.\n**${prefix.prefix}Disk** - Displays relevant info about host Storage sytem.\n**${prefix.prefix}GPU** - Displays all info about the host GPU.\n**${prefix.prefix}Memory** - Shows all relevant info about themory allocation.\n**${prefix.prefix}Memlayout** - Displays type of memory used by the host.\n**${prefix.prefix}Motherboard** - Displays host motherboard info.\n**${prefix.prefix}OSInfo** - Shows any info about the host OS.\n**${prefix.prefix}sysinfo** - Displays all info about the bots host system.\n-----------------------`},
        { name: '🎟️ Ticket Command(s):', value: `**${prefix.prefix}ticket** - WIP ticket system.\n-----------------------`},
        { name: '⚙️ Utility Commands:', value: `**${prefix.prefix}pfp** - If you want to be "that guy" and steal someones profile picture... :)\n**${prefix.prefix}ping** - Check this bots ping.\n**${prefix.prefix}stats** - Check the bots server statistics.\n**${prefix.prefix}help** - Shows an interactive help menu!\n**${prefix.prefix}info** - Displays any relevant info about the bot.\n**${prefix.prefix}userinfo** - Display info about another users account.\n**${prefix.prefix}cmds** - Displays this menu! (duh.)\n**${prefix.prefix}time** - WIP until bot has funding. \¯\\\_\(\ツ\)\_\/\¯\n-----------------------`},
	    { name: '⚒️ Administration Commands:', value: `**${prefix.prefix}Reload** - Reloads the bot and restarts it.\n**${prefix.prefix}kick** - Kick any rule breakers!\n**${prefix.prefix}ban** - Show who's boss by removing a user indefinitely.\n**${prefix.prefix}purge** - Gets rid of the horrible spam messages for you.\n**${prefix.prefix}mute** - Silence anyone who is against you!\n**${prefix.prefix}warn** - Warn someone should they break a minor rule.\n**${prefix.prefix}logs** - Creates a new channel specifically to admins for logging.\n**${prefix.prefix}unban** - This feature is currently a work in progress, stay tuned.\n**${prefix.prefix}unmute** - Unmute a user manually, rather than auto-unmute.\n**${prefix.prefix}Hoist** - Allows for users to give themselves higher roles.\n**${prefix.prefix}delrole** - Deletes a selected role in your guild.\n-----------------------`}, */
    )
    .setThumbnail(`${message.author.displayAvatarURL({
        dynamic: true
    })}`)
    .setTimestamp()
    .setFooter(`${message.author.username}, More is soon to come, Dm YahYett#1709 for suggestions!`)
    message.channel.send(cmdEmbed);
}
